### ISSUE TITLE
Pouchdb change events are deprecated

### ISSUE THREAD

**Issue by obdulia-losantos** [eHealthAfrica/kazana-server#30]
In future pouchdb versions (>`4.0.3`) the change events will be `change`, `complete` and `error` and `create`, `update` and `delete` will be deleted.
pouchdb/pouchdb@83a4a0b

In `lib/compose-plugin.js#L181-L192` the used events are `create`, `update` and `delete`. Should it be modified?

**Comment by jo** [comment]
yes, it shold.

**Comment by jo** [comment]
Here: https://github.com/eHealthAfrica/kazana-server/pull/47

**Comment by patriciagarcia** [comment]
@jo, this was closed by #47, right?

**Comment by jo** [comment]
Yes
