### ISSUE TITLE
Improve error messages for plugin init failures on startup

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/kazana-server#41]
When a plugin registration fails there is no information logged which plugin is.

Example error message:

```sh
{ [not_found: missing]
  status: 404,
  name: 'not_found',
  message: 'missing',
  error: true,
  reason: 'missing' }
/kazana/bin/server:76
      throw new Error(error.message)
      ^

Error: missing
    at /kazana/bin/server:76:13
    at /kazana/node_modules/kazana-server/index.js:146:14
    at /kazana/node_modules/kazana-server/node_modules/async/lib/async.js:697:13
    at /kazana/node_modules/kazana-server/node_modules/async/lib/async.js:52:16
    at done (/kazana/node_modules/kazana-server/node_modules/async/lib/async.js:243:17)
    at /kazana/node_modules/kazana-server/node_modules/async/lib/async.js:44:16
    at /kazana/node_modules/kazana-server/node_modules/async/lib/async.js:694:17
    at /kazana/node_modules/kazana-server/node_modules/async/lib/async.js:173:37
    at /kazana/node_modules/kazana-server/index.js:132:9
    at /kazana/node_modules/kazana-server/node_modules/hapi/lib/plugin.js:261:16
```

**Comment by patriciagarcia** [comment]
Might be related https://github.com/eHealthAfrica/guinea-connect/issues/50

**Comment by patriciagarcia** [comment]
@johannes, does this fix https://github.com/eHealthAfrica/kazana-server/pull/59 also solve the current issue? (not sure if they are related)

**Comment by jo** [comment]
Thats not easy to check, will keep this in mind and check if I'm on it.

**Comment by johannes** [comment]
(Please don't write @johannes if you want to reach @jo as @johannes will subscribe me.
btw. Thanks for helping to make the world a better place - at least it looks like that's what you're doing from a quick look at your project!
Feel free to silently delete this comment after noticing it)

**Comment by patriciagarcia** [comment]
@johannes I am so sorry, I wrote the comment from a external tool, that doesn't have Github username autocomplete, so I didn't notice I was pinging the wrong Johannes. I'll be more careful in the future!

**Comment by jo** [comment]
Closing this for now. Will reopen if still valid.
