### ISSUE TITLE
On startup, make sure all indicators from deleted submissions are removed

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/kazana-server#76]
follow up for https://github.com/eHealthAfrica/kazana-server/pull/73#discussion_r44093432

**Comment by jo** [comment]
Not possible with current bootstrap implementation, which is based on views. See https://github.com/eHealthAfrica/kazana-transform/issues/2

**Comment by jo** [comment]
Fixed in https://github.com/eHealthAfrica/kazana-transform/pull/6
