### ISSUE TITLE
Auto-run of PouchDB server breaks Guinea Connect Universal App in dev mode

### ISSUE THREAD

**Issue by patriciagarcia** [eHealthAfrica/kazana-server#81]
latest version working is 3.3.0

@karlwestin, anything else to add? feel free also to correct anything if it's not correct.

**Comment by karl-ehealth** [comment]
just telling the story of what happened:
we were loading kazana-server ^3.0.0 in package.json
since we have a watcher in dev-mode, that looks for code-changes and restarts the server, we have set the start of the pouchdb outside the part that gets restarted on code changes, and then starting a kazana-server inside our watched handler. The idea was that pouchdb would stay on, and the kazana-server would restart. 

With version 3.4.0, which was covered by the semver range, kazana-server starts a pouchdb as well. We got this error:
```
[1] Error: Port 4999 is already in use.
[1] Try another one, e.g. pouchdb-server -p 5000
[1] Unhandled rejection OpenError: IO error: lock ./.db/_replicator/LOCK: Resource temporarily unavailable
```
it was pretty hard to debug

anyway not sure what the resolution is. I was asked to fill in details here. We fixed it by locking to 3.3.0 which doesn't auto-start pouchdb, so its not blocking us.

**Comment by jo** [comment]
Have you tried to `rm -rf node_modules && npm install` again?

**Comment by karl-ehealth** [comment]
yeah re-installed it all a few times. Was curious why our prod version worked and not dev. Saw the version difference in kazana-server, and tested all the way up from 2.2.6. It broke on 3.4.0 and that's when i found this commit.

**Comment by jo** [comment]
I moved the pouchdb server start logic from kazana to kazana-server in order to have it available via api in the tests. How do you restart the server?

**Comment by karl-ehealth** [comment]
with some module called `piping` https://github.com/eHealthAfrica/guinea-connect-universal-app/blob/master/bin/dev-server#L52-L56

**Comment by jo** [comment]
Three possibilities:
- do not mind to restart pouchdb on every change (and remove https://github.com/eHealthAfrica/guinea-connect-universal-app/blob/master/bin/dev-server#L29-L45)
- configure the server in https://github.com/eHealthAfrica/guinea-connect-universal-app/blob/master/bin/startKazana.js with the couchdb adapter which you have manually started (`'localhost:' + config.backend.port`)
- we can implement a flag `no-spawn-pouchdb-server` in `kazana-server`

**Comment by karl-ehealth** [comment]
i tried to do option 2), and pass in the config.backend with couchdb and the url, but because the whole configuration is re-read here, https://github.com/eHealthAfrica/kazana-server/blob/master/index.js#L73 the options get overwritten and the pouchdbserver is started anyway

**Comment by jo** [comment]
This sounds like a bug. @gr2m any ideas?

**Comment by gr2m** [comment]
@karl-ehealth do you have code with which I can reproduce the issue? I can look into it

**Comment by karl-ehealth** [comment]
https://github.com/eHealthAfrica/guinea-connect-universal-app/tree/kazana-error start with `kazana_formhub__token=XXX npm run dev` the token can be found in the spreadsheet, under Formhub, next to Guinea Connect

**Comment by karl-ehealth** [comment]
it seems to me like the config passed in as arguments kazana-server is completely ignored, and it only reads config files

**Comment by gr2m** [comment]
I'm checking

**Comment by karl-ehealth** [comment]
forgot to tell you, this is the place where im trying to override config
https://github.com/eHealthAfrica/guinea-connect-universal-app/blob/kazana-error/bin/startKazana.js#L49

**Comment by gr2m** [comment]
try

```js
config = {
  kazana: {
    backend: {
      name: 'couchdb',
      location: 'http://localhost:4999'
    }
  }
}
```

**Comment by karl-ehealth** [comment]
thanks i just found this seems to work:
```
config = {
  config: {
    backend: {
      name: 'couchdb',
      location: 'http://localhost:4999'
    }
  }
}
```
('kazana' did not)

**Comment by karl-ehealth** [comment]
thanks for helping @gr2m
